// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.2
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xcost_func.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XCost_func_CfgInitialize(XCost_func *InstancePtr, XCost_func_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Lite1_BaseAddress = ConfigPtr->Lite1_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XCost_func_Start(XCost_func *InstancePtr) {
    u32 Data;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XCost_func_ReadReg(InstancePtr->Lite1_BaseAddress, XCOST_FUNC_LITE1_ADDR_AP_CTRL) & 0x80;
    XCost_func_WriteReg(InstancePtr->Lite1_BaseAddress, XCOST_FUNC_LITE1_ADDR_AP_CTRL, Data | 0x01);
}

u32 XCost_func_IsDone(XCost_func *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XCost_func_ReadReg(InstancePtr->Lite1_BaseAddress, XCOST_FUNC_LITE1_ADDR_AP_CTRL);
    return (Data >> 1) & 0x1;
}

u32 XCost_func_IsIdle(XCost_func *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XCost_func_ReadReg(InstancePtr->Lite1_BaseAddress, XCOST_FUNC_LITE1_ADDR_AP_CTRL);
    return (Data >> 2) & 0x1;
}

u32 XCost_func_IsReady(XCost_func *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XCost_func_ReadReg(InstancePtr->Lite1_BaseAddress, XCOST_FUNC_LITE1_ADDR_AP_CTRL);
    // check ap_start to see if the pcore is ready for next input
    return !(Data & 0x1);
}

void XCost_func_EnableAutoRestart(XCost_func *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XCost_func_WriteReg(InstancePtr->Lite1_BaseAddress, XCOST_FUNC_LITE1_ADDR_AP_CTRL, 0x80);
}

void XCost_func_DisableAutoRestart(XCost_func *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XCost_func_WriteReg(InstancePtr->Lite1_BaseAddress, XCOST_FUNC_LITE1_ADDR_AP_CTRL, 0);
}

void XCost_func_Set_quantidadeCidades(XCost_func *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XCost_func_WriteReg(InstancePtr->Lite1_BaseAddress, XCOST_FUNC_LITE1_ADDR_QUANTIDADECIDADES_DATA, Data);
}

u32 XCost_func_Get_quantidadeCidades(XCost_func *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XCost_func_ReadReg(InstancePtr->Lite1_BaseAddress, XCOST_FUNC_LITE1_ADDR_QUANTIDADECIDADES_DATA);
    return Data;
}

void XCost_func_Set_quantidadeItens(XCost_func *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XCost_func_WriteReg(InstancePtr->Lite1_BaseAddress, XCOST_FUNC_LITE1_ADDR_QUANTIDADEITENS_DATA, Data);
}

u32 XCost_func_Get_quantidadeItens(XCost_func *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XCost_func_ReadReg(InstancePtr->Lite1_BaseAddress, XCOST_FUNC_LITE1_ADDR_QUANTIDADEITENS_DATA);
    return Data;
}

void XCost_func_Set_capacidadeMochila(XCost_func *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XCost_func_WriteReg(InstancePtr->Lite1_BaseAddress, XCOST_FUNC_LITE1_ADDR_CAPACIDADEMOCHILA_DATA, Data);
}

u32 XCost_func_Get_capacidadeMochila(XCost_func *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XCost_func_ReadReg(InstancePtr->Lite1_BaseAddress, XCOST_FUNC_LITE1_ADDR_CAPACIDADEMOCHILA_DATA);
    return Data;
}

void XCost_func_Set_velocidadeMaxima(XCost_func *InstancePtr, u64 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XCost_func_WriteReg(InstancePtr->Lite1_BaseAddress, XCOST_FUNC_LITE1_ADDR_VELOCIDADEMAXIMA_DATA, (u32)(Data));
    XCost_func_WriteReg(InstancePtr->Lite1_BaseAddress, XCOST_FUNC_LITE1_ADDR_VELOCIDADEMAXIMA_DATA + 4, (u32)(Data >> 32));
}

u64 XCost_func_Get_velocidadeMaxima(XCost_func *InstancePtr) {
    u64 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XCost_func_ReadReg(InstancePtr->Lite1_BaseAddress, XCOST_FUNC_LITE1_ADDR_VELOCIDADEMAXIMA_DATA);
    Data += (u64)XCost_func_ReadReg(InstancePtr->Lite1_BaseAddress, XCOST_FUNC_LITE1_ADDR_VELOCIDADEMAXIMA_DATA + 4) << 32;
    return Data;
}

void XCost_func_Set_velocidadeMinima(XCost_func *InstancePtr, u64 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XCost_func_WriteReg(InstancePtr->Lite1_BaseAddress, XCOST_FUNC_LITE1_ADDR_VELOCIDADEMINIMA_DATA, (u32)(Data));
    XCost_func_WriteReg(InstancePtr->Lite1_BaseAddress, XCOST_FUNC_LITE1_ADDR_VELOCIDADEMINIMA_DATA + 4, (u32)(Data >> 32));
}

u64 XCost_func_Get_velocidadeMinima(XCost_func *InstancePtr) {
    u64 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XCost_func_ReadReg(InstancePtr->Lite1_BaseAddress, XCOST_FUNC_LITE1_ADDR_VELOCIDADEMINIMA_DATA);
    Data += (u64)XCost_func_ReadReg(InstancePtr->Lite1_BaseAddress, XCOST_FUNC_LITE1_ADDR_VELOCIDADEMINIMA_DATA + 4) << 32;
    return Data;
}

void XCost_func_Set_aluguel(XCost_func *InstancePtr, u64 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XCost_func_WriteReg(InstancePtr->Lite1_BaseAddress, XCOST_FUNC_LITE1_ADDR_ALUGUEL_DATA, (u32)(Data));
    XCost_func_WriteReg(InstancePtr->Lite1_BaseAddress, XCOST_FUNC_LITE1_ADDR_ALUGUEL_DATA + 4, (u32)(Data >> 32));
}

u64 XCost_func_Get_aluguel(XCost_func *InstancePtr) {
    u64 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XCost_func_ReadReg(InstancePtr->Lite1_BaseAddress, XCOST_FUNC_LITE1_ADDR_ALUGUEL_DATA);
    Data += (u64)XCost_func_ReadReg(InstancePtr->Lite1_BaseAddress, XCOST_FUNC_LITE1_ADDR_ALUGUEL_DATA + 4) << 32;
    return Data;
}

void XCost_func_Set_itemValor(XCost_func *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XCost_func_WriteReg(InstancePtr->Lite1_BaseAddress, XCOST_FUNC_LITE1_ADDR_ITEMVALOR_DATA, Data);
}

u32 XCost_func_Get_itemValor(XCost_func *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XCost_func_ReadReg(InstancePtr->Lite1_BaseAddress, XCOST_FUNC_LITE1_ADDR_ITEMVALOR_DATA);
    return Data;
}

void XCost_func_Set_itemPeso(XCost_func *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XCost_func_WriteReg(InstancePtr->Lite1_BaseAddress, XCOST_FUNC_LITE1_ADDR_ITEMPESO_DATA, Data);
}

u32 XCost_func_Get_itemPeso(XCost_func *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XCost_func_ReadReg(InstancePtr->Lite1_BaseAddress, XCOST_FUNC_LITE1_ADDR_ITEMPESO_DATA);
    return Data;
}

void XCost_func_Set_inicioItensCidade(XCost_func *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XCost_func_WriteReg(InstancePtr->Lite1_BaseAddress, XCOST_FUNC_LITE1_ADDR_INICIOITENSCIDADE_DATA, Data);
}

u32 XCost_func_Get_inicioItensCidade(XCost_func *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XCost_func_ReadReg(InstancePtr->Lite1_BaseAddress, XCOST_FUNC_LITE1_ADDR_INICIOITENSCIDADE_DATA);
    return Data;
}

void XCost_func_Set_indiceItemCidade(XCost_func *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XCost_func_WriteReg(InstancePtr->Lite1_BaseAddress, XCOST_FUNC_LITE1_ADDR_INDICEITEMCIDADE_DATA, Data);
}

u32 XCost_func_Get_indiceItemCidade(XCost_func *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XCost_func_ReadReg(InstancePtr->Lite1_BaseAddress, XCOST_FUNC_LITE1_ADDR_INDICEITEMCIDADE_DATA);
    return Data;
}

void XCost_func_Set_pontoX(XCost_func *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XCost_func_WriteReg(InstancePtr->Lite1_BaseAddress, XCOST_FUNC_LITE1_ADDR_PONTOX_DATA, Data);
}

u32 XCost_func_Get_pontoX(XCost_func *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XCost_func_ReadReg(InstancePtr->Lite1_BaseAddress, XCOST_FUNC_LITE1_ADDR_PONTOX_DATA);
    return Data;
}

void XCost_func_Set_pontoY(XCost_func *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XCost_func_WriteReg(InstancePtr->Lite1_BaseAddress, XCOST_FUNC_LITE1_ADDR_PONTOY_DATA, Data);
}

u32 XCost_func_Get_pontoY(XCost_func *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XCost_func_ReadReg(InstancePtr->Lite1_BaseAddress, XCOST_FUNC_LITE1_ADDR_PONTOY_DATA);
    return Data;
}

void XCost_func_Set_percurso(XCost_func *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XCost_func_WriteReg(InstancePtr->Lite1_BaseAddress, XCOST_FUNC_LITE1_ADDR_PERCURSO_DATA, Data);
}

u32 XCost_func_Get_percurso(XCost_func *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XCost_func_ReadReg(InstancePtr->Lite1_BaseAddress, XCOST_FUNC_LITE1_ADDR_PERCURSO_DATA);
    return Data;
}

void XCost_func_Set_mochila(XCost_func *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XCost_func_WriteReg(InstancePtr->Lite1_BaseAddress, XCOST_FUNC_LITE1_ADDR_MOCHILA_DATA, Data);
}

u32 XCost_func_Get_mochila(XCost_func *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XCost_func_ReadReg(InstancePtr->Lite1_BaseAddress, XCOST_FUNC_LITE1_ADDR_MOCHILA_DATA);
    return Data;
}

u64 XCost_func_Get_resposta(XCost_func *InstancePtr) {
    u64 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XCost_func_ReadReg(InstancePtr->Lite1_BaseAddress, XCOST_FUNC_LITE1_ADDR_RESPOSTA_DATA);
    Data += (u64)XCost_func_ReadReg(InstancePtr->Lite1_BaseAddress, XCOST_FUNC_LITE1_ADDR_RESPOSTA_DATA + 4) << 32;
    return Data;
}

u32 XCost_func_Get_resposta_vld(XCost_func *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XCost_func_ReadReg(InstancePtr->Lite1_BaseAddress, XCOST_FUNC_LITE1_ADDR_RESPOSTA_CTRL);
    return Data & 0x1;
}

void XCost_func_InterruptGlobalEnable(XCost_func *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XCost_func_WriteReg(InstancePtr->Lite1_BaseAddress, XCOST_FUNC_LITE1_ADDR_GIE, 1);
}

void XCost_func_InterruptGlobalDisable(XCost_func *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XCost_func_WriteReg(InstancePtr->Lite1_BaseAddress, XCOST_FUNC_LITE1_ADDR_GIE, 0);
}

void XCost_func_InterruptEnable(XCost_func *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XCost_func_ReadReg(InstancePtr->Lite1_BaseAddress, XCOST_FUNC_LITE1_ADDR_IER);
    XCost_func_WriteReg(InstancePtr->Lite1_BaseAddress, XCOST_FUNC_LITE1_ADDR_IER, Register | Mask);
}

void XCost_func_InterruptDisable(XCost_func *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XCost_func_ReadReg(InstancePtr->Lite1_BaseAddress, XCOST_FUNC_LITE1_ADDR_IER);
    XCost_func_WriteReg(InstancePtr->Lite1_BaseAddress, XCOST_FUNC_LITE1_ADDR_IER, Register & (~Mask));
}

void XCost_func_InterruptClear(XCost_func *InstancePtr, u32 Mask) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XCost_func_WriteReg(InstancePtr->Lite1_BaseAddress, XCOST_FUNC_LITE1_ADDR_ISR, Mask);
}

u32 XCost_func_InterruptGetEnabled(XCost_func *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XCost_func_ReadReg(InstancePtr->Lite1_BaseAddress, XCOST_FUNC_LITE1_ADDR_IER);
}

u32 XCost_func_InterruptGetStatus(XCost_func *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XCost_func_ReadReg(InstancePtr->Lite1_BaseAddress, XCOST_FUNC_LITE1_ADDR_ISR);
}

