// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.2
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef __linux__

#include "xstatus.h"
#include "xparameters.h"
#include "xcost_func.h"

extern XCost_func_Config XCost_func_ConfigTable[];

XCost_func_Config *XCost_func_LookupConfig(u16 DeviceId) {
	XCost_func_Config *ConfigPtr = NULL;

	int Index;

	for (Index = 0; Index < XPAR_XCOST_FUNC_NUM_INSTANCES; Index++) {
		if (XCost_func_ConfigTable[Index].DeviceId == DeviceId) {
			ConfigPtr = &XCost_func_ConfigTable[Index];
			break;
		}
	}

	return ConfigPtr;
}

int XCost_func_Initialize(XCost_func *InstancePtr, u16 DeviceId) {
	XCost_func_Config *ConfigPtr;

	Xil_AssertNonvoid(InstancePtr != NULL);

	ConfigPtr = XCost_func_LookupConfig(DeviceId);
	if (ConfigPtr == NULL) {
		InstancePtr->IsReady = 0;
		return (XST_DEVICE_NOT_FOUND);
	}

	return XCost_func_CfgInitialize(InstancePtr, ConfigPtr);
}

#endif

